# version of circleci config to use
version: 2.1

# orbs to use for the project
# information: https://circleci.com/orbs/
orbs:
  node: circleci/node@5.0.0

executors:
  node-executor:
    docker:
      - image: node:16.13.2

# jobs that this workflow will run
jobs:
  setup:
    # directory commands will run from by default
    # usually set to organization/repo
    working_directory: ~/API-market/oreid-react-components
    shell: /bin/bash --login -e
    executor: node-executor
    steps:
      # checkout the code. Because the default working_directory is the name of the repo
      # we need to go up a directory thus the `path: ".."`
      - checkout
      # call `yarn install`
      - node/install-packages:
          pkg-manager: yarn
      # save the installed modules and configured repo for the following steps
      - persist_to_workspace:
          root: ~/API-market
          paths:
            - oreid-react-components

  # job to run the tests
  test:
    # directory commands will run from by default
    # usually set to organization/repo
    working_directory: ~/API-market/oreid-react-components
    shell: /bin/bash --login -e
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/API-market
      # call the linter
      - run: echo "we should fix the linter and tests"
      # - run: yarn run lint
      # - run: yarn run test

  deploy:
    # directory commands will run from by default
    # usually set to organization/repo
    working_directory: ~/API-market/oreid-react-components
    shell: /bin/bash --login -e
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/API-market
      # get npmrc token
      - run: echo $NPMRC | base64 -d > ~/.npmrc
      - run: yarn build
      - run: yarn lint
      # check all package.json versions and publish any that haven't been published
      - run: npx lerna publish from-package --yes

# define the jobs to run
workflows:
  build_and_test:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - deploy:
          requires:
            - test
          # only run deploy step on tags
          context:
            - global-env
          filters:
            # only publish on merges to master
            branches:
              only:
                - master
